AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template for AWS App Runner Service (Free Tier Eligible) and ECR Repository.

Parameters:
  AppRunnerServiceName:
    Type: String
    Default: mvp-app-runner
    Description: The name of the App Runner service.
  ECRRepositoryName:
    Type: String
    Default: mvp-app-repo
    Description: The name of the ECR repository.

Resources:
  # 1. ECR Repository (Created by this stack)
  AppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRRepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Name
          Value: !Ref ECRRepositoryName

  # 2. IAM Role for App Runner to pull images from ECR
  AppRunnerServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
      Tags:
        - Key: Name
          Value: !Sub "${AppRunnerServiceName}-role"

  # 3. App Runner Service
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref AppRunnerServiceName
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerServiceRole.Arn
        ImageRepository:
          ImageIdentifier: !Sub "${AppRepository.RepositoryUri}:latest" # Use the ECR created above
          ImageRepositoryType: ECR
      InstanceConfiguration:
        Cpu: "1024" # 1 vCPU (Free Tier Eligible)
        Memory: "2048" # 2 GB (Free Tier Eligible)
      HealthCheckConfiguration:
        Path: "/" # Assuming the app has a root endpoint
        Protocol: HTTP
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5
      Tags:
        - Key: Name
          Value: !Ref AppRunnerServiceName

Outputs:
  AppRunnerServiceUrl:
    Description: The URL of the App Runner service
    Value: !GetAtt AppRunnerService.ServiceUrl
  ECRRepositoryUri:
    Description: The URI of the ECR Repository
    Value: !GetAtt AppRepository.RepositoryUri