AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repositories for ProyectoFestivos

Parameters:
  ProjectName:
    Type: String
    Default: festivos-api
  Environment:
    Type: String
    Default: staging
  #ECRRepoBackend:
  #  Type: String
  #ECRRepoFrontend:
  #  Type: String

Resources:
  # ECR repos
  ECRBackend:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectName}-backend" #!Ref ECRRepoBackend
      LifecyclePolicy:
        LifecyclePolicyText:
          Fn::Sub: |
            {
              "rules": [
                {"rulePriority": 1, "description": "Keep last 10 images", "selection": {"tagStatus": "any", "countType": "imageCountMoreThan", "countNumber": 10}, "action": {"type": "expire"}}
              ]
            }

  ECRFrontend:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ProjectName}-frontend" #!Ref ECRRepoFrontend
      LifecyclePolicy:
        LifecyclePolicyText:
          Fn::Sub: |
            {
              "rules": [
                {"rulePriority": 1, "description": "Keep last 10 images", "selection": {"tagStatus": "any", "countType": "imageCountMoreThan", "countNumber": 10}, "action": {"type": "expire"}}
              ]
            }

Outputs:
  ECRBackendUri:
    Description: URI del repositorio ECR backend
    Value:
      Fn::GetAtt: [ECRBackend, RepositoryUri]
    Export:
      Name:
        Fn::Sub: "${ProjectName}-ecr-backend-uri"
  ECRFrontendUri:
    Description: URI del repositorio ECR frontend
    Value:
      Fn::GetAtt: [ECRFrontend, RepositoryUri]
    Export:
      Name:
        Fn::Sub: "${ProjectName}-ecr-frontend-uri"
        Fn::Sub "${ProjectName}-ecr-frontend-uri"