AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate infra for ProyectoFestivos API

Parameters:
  ProjectName:
    Type: String
    Default: festivos-api
  Environment:
    Type: String
    Default: prod
  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC donde desplegar
  SubnetIds:
    Type: CommaDelimitedList
    Description: Lista de Subnet IDs separados por comas
  DBEndpoint:
    Type: String
    Description: Endpoint de la base de datos RDS
  DBName:
    Type: String
    Default: festivos
  DBUser:
    Type: String
    Default: postgres
  DBPassword:
    Type: String
    NoEcho: true

# Import ECR URIs
Mappings:
  ECRUris:
    Backend: !ImportValue "festivos-api-ecr-backend-uri"

Resources:
  # ============================================
  # IAM Roles
  # ============================================
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-ecs-execution-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-ecs-task-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

  # ============================================
  # Security Group
  # ============================================
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${ProjectName}-ecs-sg"
      GroupDescription: Permite trafico HTTP para ECS tasks
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # ============================================
  # CloudWatch Logs
  # ============================================
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}"
      RetentionInDays: 7

  # ============================================
  # ECS Cluster
  # ============================================
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ProjectName}-cluster"

  # ============================================
  # Task Definition
  # ============================================
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ProjectName}-task"
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: !Sub "${ProjectName}-container"
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-backend:latest"
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          Environment:
            - Name: SPRING_PROFILES_ACTIVE
              Value: docker
            - Name: SPRING_DATASOURCE_URL
              Value: !Sub "jdbc:postgresql://${DBEndpoint}:5432/${DBName}"
            - Name: SPRING_DATASOURCE_USERNAME
              Value: !Ref DBUser
            - Name: SPRING_DATASOURCE_PASSWORD
              Value: !Ref DBPassword
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:8080/actuator/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60

  # ============================================
  # ECS Service
  # ============================================
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${ProjectName}-service"
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets: !Ref SubnetIds
      HealthCheckGracePeriodSeconds: 60

Outputs:
  ECSClusterName:
    Description: Nombre del cluster ECS
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${ProjectName}-cluster-name"

  ECSServiceName:
    Description: Nombre del servicio ECS
    Value: !GetAtt ECSService.Name
    Export:
      Name: !Sub "${ProjectName}-service-name"