AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template for a Free Tier eligible RDS PostgreSQL Instance.

Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: mvp-db-instance
    Description: The database instance identifier.
  DBName:
    Type: String
    Default: mvpdb
    Description: The name of the database to create.
  DBUser:
    Type: String
    Default: mvpuser
    Description: The master username for the database.
  DBPassword:
    Type: String
    NoEcho: true
    Description: The master password for the database.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the RDS instance will be launched. (Use the default VPC ID)
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for the RDS subnet group (private subnets recommended)

Resources:
  # ============================================
  # RDS Subnet Group
  # ============================================
  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds: !Ref SubnetIds
      DBSubnetGroupName: !Sub "${DBInstanceIdentifier}-subnet-group"

  # ============================================
  # Security Group for RDS
  # ============================================
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS PostgreSQL instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          # Para pruebas se permite acceso público; en producción restringir a un CIDR o SG específico.
          CidrIp: 0.0.0.0/0

  # ============================================
  # RDS Instance
  # ============================================
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      Engine: postgres
      EngineVersion: "14.7"
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      StorageType: gp2
      BackupRetentionPeriod: 0
      MultiAZ: false
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      LicenseModel: postgresql-license

Outputs:
  DBEndpointAddress:
    Description: The endpoint address of the RDS instance
    Value: !GetAtt RDSInstance.Endpoint.Address
  DBEndpointPort:
    Description: The endpoint port of the RDS instance
    Value: !GetAtt RDSInstance.Endpoint.Port
  RDSSecurityGroupId:
    Description: The Security Group ID for the RDS instance
    Value: !Ref RDSSecurityGroup