AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template for a simple S3 Bucket for static content.

Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket. Must be globally unique.

Resources:
  StaticContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${S3BucketName}-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Suspended

Outputs:
  BucketName:
    Description: The name of the S3 bucket
    Value: !Ref StaticContentBucket
  BucketArn:
    Description: The ARN of the S3 bucket
    Value: !GetAtt StaticContentBucket.Arn